### ISSUE TITLE
Create CELPA organization?

### ISSUE THREAD

**Issue by jcs090218** [celpa/celpa#11]
Hi @conao3,

Would you consider making celpa to an organization? I think it would be great to know who are willing to contribute to celpa, and maybe one day this repo can be one great alternative compare to melpa? I think having competition is always good for technology to grow. I have made few PRs (#7, #8, #9, #10) to make a bit more differences comparing CELPA and MELPA. 

Let me know what you think! Thanks!

**Comment by conao3** [comment]
After some consideration, I make celpa into org. Let's make another Emacs Lisp Package Archive!

**Comment by jcs090218** [comment]
That's awesome! Glad you made this decision! :D I don't know how far we can reach but make CELPA an another alternative would definitely help Emacs Community. 🎉
