### ISSUE TITLE
Unknown license from GitHub

### ISSUE THREAD

**Issue by jcs090218** [celpa/celpa#14]
For some reason, GitHub aren't able to detect our [LICENSE.md](https://github.com/celpa/celpa/blob/master/LICENSE.md) file from the repository. 😕

**Comment by conao3** [comment]
Rename LICENSE.md to LICENSE? I'm fine with it.

**Comment by jcs090218** [comment]
> Rename LICENSE.md to LICENSE? I'm fine with it.

I have tried rename it but it does not work. We would have to change the file content to valid GPLv3.

I have also file a ticket to GitHub support. Maybe they would know why? 😕

**Comment by conao3** [comment]
OK. We wait for the support reply.

**Comment by jcs090218** [comment]
I think Melpa added the license when it can still be detected by GitHub license library. So there is no way to have the same license with Melpa. Let's add a new license to overwrite the old one! :)

**Comment by conao3** [comment]
OK, thanks!
