### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Silex** [celpa/celpa#15]
Why does this exist? Why the "fork" from MELPA?

I think this will be the number one FAQ so feel free to add your answer in the README :-)

**Comment by conao3** [comment]
Because I find it just useful. Would you like to be the maintainer? :)

**Comment by jcs090218** [comment]
> Why does this exist? Why the "fork" from MELPA?

Hi @Silex, I would say CELPA isn't moving away from MELPA. As you can see, the front page of CELPA has mentioned MELPA and probably should be use together. There are probably no good reasons for CELPA to exist yet we believed that creating another package archive alternative can benefits the Emacs community. And we do find CELPA being useful to us.

On the other hand, we are also looking for other strategy to make this a better alternative. Please feel free to share you thoughts if you have any. :)

**Comment by Silex** [comment]
@conao3: no, I already don't have enough time to maintain my own packages :cry: 
@jcs090218: thanks for the answer, the only reasons I can think of for CELPA existence is "MELPA refused my package" and/or "it's my archive I do what I want", which personnaly I solve by using a private git repo or whatever, but I can see how it's useful to you.
