### ISSUE TITLE
Everything is down?

### ISSUE THREAD

**Issue by 101-writing** [celpa/celpa#19]
Hi,

It looks like I can't access CELPA. Ie: https://celpa.org/ is down, and trying to get the packages from emacs yields `Debugger entered--Lisp error: (error "celpa.org/443 Name or service not known")`

**Comment by jcs090218** [comment]
The domain is https://celpa.conao3.com/.

**Comment by 101-writing** [comment]
@jcs090218 
Then you should know that the `README.md` is not up-to-date, the installation instructions and the archive index page both refer to celpa.org

Thanks though :)

**Comment by jcs090218** [comment]
Ah, yes. I will update it ASAP! Thanks for the issue report!
