### ISSUE TITLE
Move all my packages to celpa?

### ISSUE THREAD

**Issue by jcs090218** [celpa/celpa#25]
@conao3 I'm planning to move all my packages from MELPA to CELPA. Would you mind if I do that? 😖 

Probably everything on this list, see https://melpa.org/#/?q=jcs-elpa

Thanks!

**Comment by jcs090218** [comment]
Alright, I have eventually decided to host my own elpa ([jcs-elpa](https://github.com/jcs-emacs/jcs-elpa)) using the `github-elpa` package. Sorry for the noise here!

Do you want me to remove all my packages here or it's okay to leave them as it is!? And thanks for hosting CELPA! I serves me well these years! ❤️ 🙏

**Comment by conao3** [comment]
Nice. As you can see from my activity, I don't spend much time on Emacs or on OSS.
I think it is great that @jcs090218 is making ELPA more manageable for you. I support it.

Now, I think CELPA is a good way to get back to my personal ELPA. Maybe I will use github-ELPA as well.

If there are many ELPA, the conflicts of packages with the same name might be a new problem. And maybe we need a curated ELPA to mediate it lol.

Anyway, thanks for all your work on CELPA.
It is a better thing that your package recipes in CELPA should be removed with sufficient announcements and subsequent advice.

**Comment by jcs090218** [comment]
> Nice. As you can see from my activity, I don't spend much time on Emacs or on OSS.

😢 👍 

> Anyway, thanks for all your work on CELPA.
It is a better thing that your package recipes in CELPA should be removed with sufficient announcements and subsequent advice.

Good advice, I might announce it on my twitter. Anyways, I have submitted the PR in #34.

**Comment by conao3** [comment]
Merged!

At the end of this month I will dissolve the celpa-organization and this celpa repository will be back under the conao3 namespace (if possible)

**Comment by jcs090218** [comment]
And again, thank you so much for everything you have done to CELPA! ❤️ 🚀 I appreciate it! 🙏
