### ISSUE TITLE
Logo for Celpa?

### ISSUE THREAD

**Issue by jcs090218** [celpa/celpa#8]
I just created a logo for Celpa! :)

![logo](https://user-images.githubusercontent.com/8685505/110280217-6b6e6e80-8015-11eb-94d4-d0e2e4efd827.png)

@conao3 I think we can move Celpa to the next stage? Instead of just orphaned-driven archive, can we add more contribution guidelines so there could be more users contribute to Celpa? WDYT?

**Comment by conao3** [comment]
LGTM! but bit scary...? Anyway, thanks for your work!

**Comment by jcs090218** [comment]
> LGTM! but bit scary...? Anyway, thanks for your work!

Lol. I made this logo base on the banner color `#222222`. I thought this might be something you like? :0 I think this could be our temporary logo, and we could swap it later in the future. 👍

**Comment by jcs090218** [comment]
@conao3 If you accept this logo, can you set the image for our organization? :D Thanks!

**Comment by jcs090218** [comment]
I saw you set me as the owner! Thanks! :)
